import { Component, OnInit, ElementRef, ViewChild } from '@angular/core';
import {
  IonHeader,
  IonToolbar,
  IonTitle,
  IonContent,
  IonButton,
  IonItem,
  IonLabel,
  IonInput,
  IonList,
  AlertController, IonIcon
} from '@ionic/angular/standalone';
import { ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { StorageService } from '../services/storage.service';
import html2canvas from 'html2canvas';
import { Share } from '@capacitor/share';
import { Filesystem, Directory } from '@capacitor/filesystem';
import { FormsModule } from '@angular/forms';
import { VoiceService } from '../services/voice.service';
import { SocialSharing } from '@awesome-cordova-plugins/social-sharing/ngx';



@Component({
  selector: 'app-bill',
  templateUrl: './bill.page.html',
  styleUrls: ['./bill.page.scss'],
  standalone: true,
  providers: [SocialSharing],
  imports: [
    CommonModule,
    FormsModule,
    IonHeader,
    IonToolbar,
    IonTitle,
    IonContent,
    IonButton,
    IonItem,
    IonLabel,
    IonInput,
    IonList, IonIcon
  ],
})
export class BillPage implements OnInit {
  @ViewChild('billCard', { static: false }) billCard!: ElementRef;

  farmerName = '';
  fieldName = '';
  ratePerHour = 1800;
  totalMinutes = 0;
  totalHours = 0;
  totalAmount = 0;

  startTime = '';
  endTime = '';
  mobile = '';
  address = '';

  stopPeriods: { start: string; end: string }[] = [];
  today = new Date();

  // UI flags to prevent double taps
  isFarmerListening = false;
  isAddressListening = false;

  constructor(
    private router: Router,
    private storage: StorageService,
    private alertCtrl: AlertController,
    private voice: VoiceService,
    private cdr: ChangeDetectorRef,
    private socialSharing: SocialSharing
  ) { }

  async ngOnInit() {
    const navData = this.router.getCurrentNavigation()?.extras.state;
    if (navData) {
      this.totalMinutes = navData['totalMinutes'] || 0;
      this.totalHours = this.totalMinutes / 60;
      this.startTime = navData['startTime'] || '';
      this.endTime = navData['endTime'] || '';
      this.stopPeriods = navData['stopPeriods'] || [];
    }

    const savedRate = await this.storage.get('rate');
    if (savedRate) this.ratePerHour = savedRate;

    this.calculate();
  }

  calculate() {
    const hrs = this.totalHours || 0;
    const rate = Number(this.ratePerHour) || 0;
    this.totalAmount = +(hrs * rate).toFixed(2);
  }

  async saveRate() {
    await this.storage.set('rate', this.ratePerHour);
  }

  /** 📤 Share Bill - supports both Image (native share) and WhatsApp (text only) */
  async shareBill(mode: 'native' | 'whatsapp' = 'native') {
    // 1) Capture the bill as an image
    const el = this.billCard.nativeElement as HTMLElement;
    const canvas = await html2canvas(el, { scale: 2 });
    const imgData = canvas.toDataURL('image/jpeg', 0.95);

    // 2) Persist to device so Share API can attach file
    const base64Data = imgData.split(',')[1];
    const fileName = `harvester_bill_${Date.now()}.jpg`;

    await Filesystem.writeFile({
      path: fileName,
      data: base64Data,
      directory: Directory.Cache,
    });

    const { uri } = await Filesystem.getUri({
      path: fileName,
      directory: Directory.Cache,
    });

    // WhatsApp expects a file:// URI — ensure correct format
    const fileUri = uri.startsWith('file://') ? uri : 'file://' + uri.replace('content://', '');
    console.log('Prepared file URI:', fileUri);


    // 3) Save to history
    await this.storage.addBill({
      id: Date.now().toString(),
      farmerName: this.farmerName || 'Unknown',
      fieldName: this.fieldName || '',
      totalHours: this.totalHours,
      ratePerHour: this.ratePerHour,
      totalAmount: this.totalAmount,
      address: this.address,
      mobile: this.mobile,
      date: new Date().toISOString(),
    });

    // 4) Build detailed text (for WhatsApp or caption)
    const stopLines = this.stopPeriods.length
      ? this.stopPeriods.map((s, i) => `   ${i + 1}. ${s.start} → ${s.end}`).join('\n')
      : '   None';

    const message = `
🌾 *Harvester Bill Summary*
────────────────────────────
🧑‍🌾 Farmer: ${this.farmerName || '—'}
📞 Mobile: ${this.mobile || '—'}
📍 Address: ${this.address || '—'}
🏞️ Field: ${this.fieldName || '—'}
🕐 Start: ${this.startTime || '—'}
🏁 End: ${this.endTime || '—'}
⏸ Stops:
${stopLines}
⏱️ Total: ${this.totalHours.toFixed(2)} hrs
💰 Rate: ₹${this.ratePerHour} / hr
📄 Amount: ₹${this.totalAmount.toFixed(2)}
────────────────────────────
Generated by *Harvester Meter* ✅
`.trim();

    if (mode === 'whatsapp') {
      const alert = await this.alertCtrl.create({
        header: 'Send via WhatsApp',
        message: 'Enter WhatsApp number (10 digits)',
        inputs: [{ name: 'phone', type: 'tel', placeholder: 'Ex: 9876543210' }],
        buttons: [
          { text: 'Cancel', role: 'cancel' },
          { text: 'Send', role: 'confirm' },
        ],
      });
      await alert.present();
      const { data, role } = await alert.onDidDismiss();
      if (role !== 'confirm') return;

      const phoneNumber = (data?.values?.phone || '').trim();
      if (!/^[0-9]{10}$/.test(phoneNumber)) {
        await this.voice.speak('సరైన నంబర్ ఇవ్వండి');
        return;
      }

      const whatsappNumber = `91${phoneNumber}`;

      try {
        console.log('Sharing via WhatsApp →', whatsappNumber, fileUri);
        await this.socialSharing.shareViaWhatsAppToPhone(
          whatsappNumber,
          message,  // text caption
          fileUri,  // full image URI (must be file://)
          undefined
        );

        await this.voice.speak('బిల్ షేర్ చేయబడింది');
      } catch (err) {
        console.error('❌ WhatsApp share failed:', err);
        await this.voice.speak('షేర్ చేయడంలో సమస్య వచ్చింది');

        // fallback: text-only share (if file fails)
        const fallbackUrl = `https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`;
        window.open(fallbackUrl, '_blank');
      }
    } else {
      await Share.share({
        title: 'Harvester Bill',
        text: message,
        files: [fileUri],
        dialogTitle: 'Share Harvester Bill',
      });
    }
  }
  /** 🎙 Voice input for farmer name */
  async recordFarmerName() {
    if (this.isFarmerListening || this.isAddressListening) return;
    this.isFarmerListening = true;

    await this.voice.speak('దయచేసి రైతు పేరు చెప్పండి');
    await new Promise(r => setTimeout(r, 900)); // give TTS time to finish

    const { text } = await this.voice.listenFor('farmer', { timeoutMs: 8000 });
    if (this.isFarmerListening) {
      if (text) {
        this.farmerName = text;
        await this.voice.speak(`రైతు పేరు ${text}`);
      } else {
        await this.voice.speak('పేరు వినిపించలేదు, మళ్లీ ప్రయత్నించండి');
      }
    }

    this.isFarmerListening = false;
    this.cdr.detectChanges();
  }

  /** 🎙 Voice input for address */
  async recordAddress() {
    if (this.isFarmerListening || this.isAddressListening) return;
    this.isAddressListening = true;

    await this.voice.speak('దయచేసి చిరునామా లేదా గ్రామం పేరు చెప్పండి');
    await new Promise(r => setTimeout(r, 900));

    const { text } = await this.voice.listenFor('address', { timeoutMs: 9000 });
    if (this.isAddressListening) {
      if (text) {
        this.address = text;
        await this.voice.speak(`చిరునామా ${text}`);
      } else {
        await this.voice.speak('చిరునామా వినిపించలేదు, మళ్లీ ప్రయత్నించండి');
      }
    }

    this.isAddressListening = false;
    this.cdr.detectChanges();
  }


  goHome() {
    this.router.navigateByUrl('/');
  }

  goToHistory() {
    this.router.navigateByUrl('/history');
  }


}
